name: maze_ai
description: "A new Flutter project."

version: 0.0.1+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_route: ^8.2.0
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  envied: ^0.5.4
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_gemini: ^2.0.4
  flutter_highlighter: ^0.1.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.3
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10
  fpdart: ^1.1.0
  get_it: ^7.7.0
  hooks_riverpod: ^2.5.1
  image_picker: ^1.1.2
  injectable: ^2.4.2
  intl: ^0.19.0
  lottie: ^3.1.2
  url_launcher: ^6.3.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  change_app_package_name: ^1.3.0
  envied_generator: ^0.5.4
  flutter_gen_runner: ^5.6.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  lint: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/animations/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600

flutter_gen:
  assets:
    enabled: true
  integrations:
    flutter_svg: true
